spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul
        timezone:
          default_storage: NORMALIZE
  web:
    resources:
      add-mappings: false
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration-milliseconds: 1800000
    refresh-token-expiration-milliseconds: 1209600000
  cookie:
    domain: .ninedot.p-e.kr
    secure: true
    path: /
  task:
    scheduling:
      time-zone: Asia/Seoul
  ai:
    model:
      chat: none

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite-preview-06-17:generateContent
    response-schema: ${GEMINI_RESPONSE_STRUCTURE:}
    subgoal-response-schema: ${GEMINI_SUB_GOAL_RESPONSE_STRUCTURE:}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}
  token-uri: https://oauth2.googleapis.com/token
  userinfo-uri: https://openidconnect.googleapis.com/v1/userinfo

auth:
  redirect:
    whitelist:
      - http://localhost:5173/auth/google/callback
      - https://ninedot-client.vercel.app/auth/google/callback
    default-redirect-uri: https://ninedot-client.vercel.app/auth/google/callback
