logging:
  level:
    root: DEBUG
    org.sopt36.ninedotserver: DEBUG

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
        timezone:
          default_storage: NORMALIZE
  web:
    resources:
      add-mappings: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    mixed: true
    clean-disabled: true

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-milliseconds: 1800000
  refresh-token-expiration-milliseconds: 1209600000

cookie:
  domain: .ninedot.p-e.kr
  secure: true
  path: /

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite-preview-06-17:generateContent
    response-schema: ${GEMINI_RESPONSE_STRUCTURE:}
    subgoal-response-schema: ${GEMINI_SUB_GOAL_RESPONSE_STRUCTURE:}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  token-uri: https://oauth2.googleapis.com/token
  userinfo-uri: https://openidconnect.googleapis.com/v1/userinfo

auth:
  redirect:
    whitelist:
      - http://localhost:5173/auth/google/callback
      - ${GOOGLE_REDIRECT_URI}
    default-redirect-uri: ${GOOGLE_REDIRECT_URI}
