spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${LOCAL_SPRING_DATASOURCE_URL}
    username: ${LOCAL_SPRING_DATASOURCE_USERNAME}
    password: ${LOCAL_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      add-mappings: false
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration-milliseconds: 3600000
    refresh-token-expiration-milliseconds: 604800000
  cookie:
    domain: localhost # .
    secure: false
    path: /
  task:
    scheduling:
      time-zone: Asia/Seoul
  ai:
    model:
      chat: none
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite-preview-06-17:generateContent
    response-schema: ${GEMINI_RESPONSE_STRUCTURE:}
    subgoal-response-schema: ${GEMINI_SUB_GOAL_RESPONSE_STRUCTURE:}
